export { default as getGroups } from "./group/getGroups/getGroups";
export { default as postLogin } from "./auth/login/login";
export { default as getUser } from "./user/getUser/getUser";
export { default as postResetPassword } from "./auth/resetPassword/resetPassword";
export { default as getHistory } from "./my-history/getHistory";
export { default as getTaskList } from "./task-list/getTaskList";
export { default as postTask } from "./task-list/postTask";
export { default as getArticles } from "./article/getArticles/getArticles";
export { default as getArticle } from "./article/getArticle/getArticle";
