import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import QueryProviders from "../providers";
import SidebarMobile from "@/common/Sidebar/_internal/SidebarMobile/SidebarMobile";

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.className}>
      <body className="flex flex-col tablet:flex-row pc:flex-row">
        <QueryProviders>
          {/* <Sidebar /> */}
          <SidebarMobile />
          <main>{children}</main>
        </QueryProviders>
      </body>
    </html>
  );
}
