import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import QueryProviders from "../providers";
import { Sidebar } from "@/common";
import ToasterContainer from "@/lib/toaster";

const pretendard = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.className}>
      <body className="flex flex-col tablet:flex-row pc:flex-row">
        <QueryProviders>
          <Sidebar />
          <main className="flex-1 min-w-0 bg-background-secondary">{children}</main>
          <ToasterContainer />
        </QueryProviders>
      </body>
    </html>
  );
}
